// ── Complete EGX Listed Stocks (260 stocks) ─────────────────────
// Sources: stockanalysis.com + TradingView + african-markets.com + web research
// Sectors follow GICS classification
// Last updated: June 2026

export const EGX_STOCKS: Array<{
  symbol: string;
  name: string;
  sector: string;
}> = [
  { symbol: "AALR", name: "General Company For Land Reclamation, Development & Reconstruction", sector: "Industrials" },
  { symbol: "ABUK", name: "Abu Qir Fertilizers & Chemical Industries Company (S.A.E)", sector: "Materials" },
  { symbol: "ACAMD", name: "Arab Co.,for asset management and development", sector: "Real Estate" },
  { symbol: "ACAP", name: "A Capital Holding", sector: "Industrials" },
  { symbol: "ACGC", name: "Arabia Cotton Ginning Company", sector: "Consumer Defensive" },
  { symbol: "ACTF.CA", name: "Act Financial", sector: "Financials" },
  { symbol: "ADCI", name: "The Arab Drug Company", sector: "Healthcare" },
  { symbol: "ADIB", name: "Abu Dhabi Islamic Bank - Egypt - S.A.E", sector: "Financials" },
  { symbol: "ADRI", name: "Arab Development & Real Estate Investment", sector: "Real Estate" },
  { symbol: "ADPC", name: "The Arab Dairy Products Co.", sector: "Consumer Defensive" },
  { symbol: "AFDI", name: "Al Ahly for Development & Investment", sector: "Financials" },
  { symbol: "AIFI", name: "Atlas for Investment & Food Industries SAE", sector: "Consumer Defensive" },
  { symbol: "AFMC", name: "Alexandria Flour Mills", sector: "Consumer Defensive" },
  { symbol: "AIDC", name: "Arabia for Investment and Development S.A.E.", sector: "Real Estate" },
  { symbol: "AIH", name: "Arabia Investments Holding", sector: "Industrials" },
  { symbol: "AJWA", name: "AJWA For Food Industries Co. Egypt", sector: "Consumer Defensive" },
  { symbol: "ALCN", name: "Alexandria Container & Cargo Handling Company", sector: "Industrials" },
  { symbol: "ALEX", name: "Alexandria Cement Company", sector: "Materials" },
  { symbol: "ALRA", name: "Atlas for Investment & Food Industries", sector: "Consumer Defensive" },
  { symbol: "ALUM", name: "Arab Aluminum Company (S.A.E)", sector: "Materials" },
  { symbol: "AMPI", name: "AL Moasher Pay for Electronic Payment & Collection", sector: "Financials" },
  { symbol: "APPC", name: "AL Moasher Pay (Preferred Shares)", sector: "Financials" },
  { symbol: "AMER", name: "Amer Group Holding Company S.A.E.", sector: "Consumer Discretionary" },
  { symbol: "AMES", name: "Alexandria New Medical Center", sector: "Healthcare" },
  { symbol: "AMIA", name: "Arab Moltaqa Investments Company", sector: "Industrials" },
  { symbol: "AMOC", name: "Alexandria Mineral Oils Company", sector: "Materials" },
  { symbol: "ANFI", name: "Tycoon Holding Company For Financial Investments", sector: "Financials" },
  { symbol: "APSW", name: "Unirab Polvara Spinning & Weaving Co.", sector: "Consumer Discretionary" },
  { symbol: "ARAB", name: "Arab Developers Holding", sector: "Consumer Discretionary" },
  { symbol: "ARCC", name: "Arabian Cement Company S.A.E.", sector: "Industrials" },
  { symbol: "AREH", name: "Real Estate Egyptian Consortium S.A.E", sector: "Real Estate" },
  { symbol: "ARVA", name: "Arab Valves Company", sector: "Industrials" },
  { symbol: "ASCM", name: "ASEC Company for Mining ASCOM, S.A.E", sector: "Industrials" },
  { symbol: "ASPI", name: "Aspire Capital Holding for Financial Investments", sector: "Financials" },
  { symbol: "ATLC", name: "Al Tawfeek Leasing Company", sector: "Financials" },
  { symbol: "ATQA", name: "Misr National Steel - Ataqa", sector: "Materials" },
  { symbol: "AXPH", name: "Alexandria Co. For Pharmaceuticals & Chemical Industries", sector: "Healthcare" },
  { symbol: "BIDI", name: "El Badr Investment and Development", sector: "Real Estate" },
  { symbol: "BIGP", name: "ElBarbary Investment Group", sector: "Financials" },
  { symbol: "BINV", name: "B Investments Holding S.A.E.", sector: "Financials" },
  { symbol: "BIOC", name: "GlaxoSmithKline S.A.E", sector: "Healthcare" },
  { symbol: "BONY", name: "Bonyan for Development and Trade", sector: "Real Estate" },
  { symbol: "BTFH", name: "Beltone Holding S.A.E", sector: "Financials" },
  { symbol: "CIRF", name: "Cairo Development and Investment Co.", sector: "Real Estate" },
  { symbol: "CAED", name: "Cairo Educational Services SAE", sector: "Consumer Discretionary" },
  { symbol: "CANA", name: "Suez Canal Bank (S.A.E)", sector: "Financials" },
  { symbol: "CCAP", name: "QALA For Financial Investments", sector: "Financials" },
  { symbol: "CCRS", name: "Gulf Canadian Company for Arab Real Estate Investment", sector: "Real Estate" },
  { symbol: "CEFM", name: "Middle Egypt Flour Mills", sector: "Consumer Defensive" },
  { symbol: "CERA", name: "The Arab Ceramic Co.", sector: "Industrials" },
  { symbol: "CFGH", name: "Concrete Fashion Group For Commercial and Industrial investments S.A.E", sector: "Materials" },
  { symbol: "CICH", name: "CI Capital Holding For Financial Investments (S.A.E)", sector: "Financials" },
  { symbol: "CIEB", name: "Credit Agricole - Egypt Bank (S.A.E.)", sector: "Financials" },
  { symbol: "CIRA", name: "Cairo For Investment And Real Estate Developments-CIRA Education", sector: "Real Estate" },
  { symbol: "CLHO", name: "Cleopatra Hospitals Group S.A.E.", sector: "Healthcare" },
  { symbol: "CNFN", name: "Contact Financial Holding S.A.E.", sector: "Financials" },
  { symbol: "COMI", name: "Commercial International Bank Egypt (CIB) S.A.E.", sector: "Financials" },
  { symbol: "COPR", name: "Copper for Commercial Investment & Real Estate Development", sector: "Real Estate" },
  { symbol: "COSG", name: "Cairo Oil & Soap Company", sector: "Consumer Defensive" },
  { symbol: "CPCI", name: "Kahira Pharmaceuticals & Chemical Industries Company", sector: "Healthcare" },
  { symbol: "CPME", name: "Catalyst Partners", sector: "Industrials" },
  { symbol: "CRST", name: "Creast Mark For Contracting And Real Estate Development", sector: "Industrials" },
  { symbol: "CSAG", name: "Canal Shipping Agencies Company", sector: "Industrials" },
  { symbol: "ACRO", name: "Acrow Misr", sector: "Industrials" },
  { symbol: "DCRC", name: "Delta Construction & Rebuilding Co.", sector: "Industrials" },
  { symbol: "DAPH", name: "Development & Engineering Consultants", sector: "Industrials" },
  { symbol: "DCCC", name: "Damietta Container & Cargo Handling Co.", sector: "Industrials" },
  { symbol: "DEIN", name: "Delta Insurance Company", sector: "Financials" },
  { symbol: "DGTZ", name: "I Wave Beyond Your Expectations", sector: "Industrials" },
  { symbol: "DOMT", name: "Arabian Food Industries Company (DOMTY) - S.A.E", sector: "Consumer Defensive" },
  { symbol: "DSCW", name: "Dice For Ready-Made Garments (SAE)", sector: "Consumer Discretionary" },
  { symbol: "DTPP", name: "Delta Co. For Printing & Packaging S.A.E", sector: "Industrials" },
  { symbol: "EGREF", name: "Egyptians Real Estate Fund", sector: "Real Estate" },
  { symbol: "EITP", name: "Egyptian International Touristic Projects", sector: "Consumer Discretionary" },
  { symbol: "EALR", name: "Arab Company For Land Reclamation", sector: "Real Estate" },
  { symbol: "EASB", name: "Egyptian Arabian Company (Themar) for securities Brokerage EAC", sector: "Financials" },
  { symbol: "EAST", name: "Eastern Company S.A.E", sector: "Industrials" },
  { symbol: "EBSC", name: "Osool ESB Securities Brokerage", sector: "Financials" },
  { symbol: "ECAP", name: "Al Ezz Ceramics & Porcelain Co.", sector: "Materials" },
  { symbol: "EDFM", name: "East Delta Flour Mills", sector: "Consumer Defensive" },
  { symbol: "EEII", name: "Arab Engineering Industries", sector: "Industrials" },
  { symbol: "EFIC", name: "Egyptian Financial and Industrial SAE", sector: "Industrials" },
  { symbol: "EFID", name: "Edita Food Industries Company (S.A.E)", sector: "Consumer Defensive" },
  { symbol: "EFIH", name: "e-finance for Digital and Financial Investments S.A.E.", sector: "Technology" },
  { symbol: "EGAL", name: "Egypt Aluminum", sector: "Materials" },
  { symbol: "EGAS", name: "Egypt Gas Company SAE", sector: "Energy" },
  { symbol: "EGBE", name: "Egyptian Gulf Bank (S.A.E)", sector: "Financials" },
  { symbol: "EGCH", name: "Egyptian Chemical Industries", sector: "Materials" },
  { symbol: "EGSA", name: "The Egyptian Satellite Company Nilesat", sector: "Technology" },
  { symbol: "EGTS", name: "Egyptian Resorts Company (S.A.E)", sector: "Consumer Discretionary" },
  { symbol: "EHDR", name: "Egyptians for Housing & Development Co.", sector: "Real Estate" },
  { symbol: "ELEC", name: "Electro Cable Egypt", sector: "Industrials" },
  { symbol: "ELKA", name: "Cairo for Housing and Development Company (S.A.E)", sector: "Real Estate" },
  { symbol: "ELNA", name: "El Nasr Manufacturing Agricultural Crops S.A.E", sector: "Consumer Defensive" },
  { symbol: "ELSH", name: "Al Shams Housing and Urbanization SAE", sector: "Real Estate" },
  { symbol: "ELWA", name: "El Wadi for International and Investment Development SAE", sector: "Real Estate" },
  { symbol: "EMFD", name: "Emaar Misr for Development Company (S.A.E.)", sector: "Real Estate" },
  { symbol: "ENGC", name: "Industrial Engineering Company for Construction and Development (ICON) (S.A.E)", sector: "Industrials" },
  { symbol: "EOSB", name: "El Orouba Securities Brokerage", sector: "Financials" },
  { symbol: "EPCO", name: "Egypt for Poultry", sector: "Consumer Defensive" },
  { symbol: "EPPK", name: "El Ahram Co. For Printing And Packaging SAE", sector: "Industrials" },
  { symbol: "ETEL", name: "Telecom Egypt Company", sector: "Technology" },
  { symbol: "ETRS", name: "Egyptian Transport and Commercial Services Company S.A.E.", sector: "Industrials" },
  { symbol: "EXPA", name: "Export Development Bank of Egypt (S.A.E.)", sector: "Financials" },
  { symbol: "FAIT", name: "Faisal Islamic Bank of Egypt", sector: "Financials" },
  { symbol: "FAITA", name: "Faisal Islamic Bank of Egypt (Preferred)", sector: "Financials" },
  { symbol: "FNAR", name: "Al Fanar Contracting (NILEX)", sector: "Industrials" },
  { symbol: "FERC", name: "Ferchem Misr for fertilizers and chemicals S.A.E", sector: "Materials" },
  { symbol: "FWRY", name: "Fawry for Banking Technology and Electronic Payments S.A.E.", sector: "Technology" },
  { symbol: "GBCO", name: "GB Corp", sector: "Industrials" },
  { symbol: "GDWA", name: "Gadwa for Industrial Development", sector: "Industrials" },
  { symbol: "GTHE", name: "Global Telecom Holding SAE", sector: "Technology" },
  { symbol: "GGCC", name: "Giza General - Contracting and Real Estate Investment S.A.E", sector: "Real Estate" },
  { symbol: "GGRN", name: "Go Green For Agricultural Investment And Development", sector: "Real Estate" },
  { symbol: "GIHD", name: "Gharbia Islamic Housing Development Company", sector: "Real Estate" },
  { symbol: "GMCI", name: "GMC Group For Industrial Commercial & Financial Investments", sector: "Industrials" },
  { symbol: "GOUR", name: "Gourmet Egypt.Com Foods", sector: "Consumer Defensive" },
  { symbol: "GPIM", name: "GPI for Urban Growth", sector: "Real Estate" },
  { symbol: "GPPL", name: "Golden Pyramids Plaza S.A.E.", sector: "Consumer Discretionary" },
  { symbol: "GRCA", name: "Grand Capital for Financial Investments", sector: "Financials" },
  { symbol: "GSSC", name: "General Co. For Silos & Storage", sector: "Industrials" },
  { symbol: "GTEX", name: "GTEX for Commercial and Industrial Investments S.A.E", sector: "Industrials" },
  { symbol: "GTWL", name: "Golden Textiles & Clothes Wool", sector: "Consumer Discretionary" },
  { symbol: "HCFI", name: "Holding Company for Financial Investment - Lakah Group", sector: "Financials" },
  { symbol: "HDBK", name: "Housing and Development Bank- Egypt (S.A.E)", sector: "Financials" },
  { symbol: "HELI", name: "Heliopolis Co. for Housing & Development", sector: "Real Estate" },
  { symbol: "HRHO", name: "EFG Holding Company S.A.E", sector: "Financials" },
  { symbol: "ICID", name: "International Co. For Investment & Development", sector: "Real Estate" },
  { symbol: "ICLE", name: "International Company for Leasing S.A.E.", sector: "Financials" },
  { symbol: "IDHC", name: "Integrated Diagnostics Holdings", sector: "Healthcare" },
  { symbol: "IDRE", name: "Ismailia Development and Real Estate Co", sector: "Real Estate" },
  { symbol: "IFAP", name: "International Company for Agricultural Crops", sector: "Consumer Defensive" },
  { symbol: "INFI", name: "Ismailia National Co. for Food Industries", sector: "Consumer Defensive" },
  { symbol: "IRAX", name: "El Ezz Aldekhela Steel - Alexandria", sector: "Materials" },
  { symbol: "IRON", name: "Egyptian Iron and Steel Company", sector: "Materials" },
  { symbol: "ISMA", name: "Ismailia / Misr Poultry Company S.A.E", sector: "Consumer Defensive" },
  { symbol: "ISMQ", name: "Iron & Steel for Mines & Quarries", sector: "Materials" },
  { symbol: "ESGI", name: "Egyptian Starch & Glucose", sector: "Consumer Defensive" },
  { symbol: "ISPH", name: "Ibnsina Pharma", sector: "Healthcare" },
  { symbol: "JUFO", name: "Juhayna Food Industries S.A.E.", sector: "Consumer Defensive" },
  { symbol: "KABO", name: "El-Nasr Clothing & Textiles Co. (KABO)", sector: "Consumer Discretionary" },
  { symbol: "KRDI", name: "AlKhair River for Development Agricultural Investment and Environmental Services", sector: "Consumer Defensive" },
  { symbol: "KWIN", name: "El Kahera El Watania Investment", sector: "Financials" },
  { symbol: "KZPC", name: "Kafr El Zayat For Pesticides & Chemicals Co.(S.A.E)", sector: "Materials" },
  { symbol: "KNGC", name: "El-Nasr Glass and Crystal", sector: "Industrials" },
  { symbol: "LCSW", name: "Lecico Egypt (S.A.E.)", sector: "Industrials" },
  { symbol: "LUTS", name: "Lotus Agri Capital", sector: "Industrials" },
  { symbol: "MAAL", name: "Marseille Almasreia Alkhalegeya For Holding Investment SAE", sector: "Financials" },
  { symbol: "MASR", name: "Madinet Masr For Housing and Development", sector: "Real Estate" },
  { symbol: "MBSC", name: "Misr Beni Suef Cement Co. S.A.E", sector: "Industrials" },
  { symbol: "MCQE", name: "Misr Cement (Qena) Company (S.A.E)", sector: "Industrials" },
  { symbol: "MCRO", name: "Macro Group Pharmaceuticals (Macro Capital) S.A.E", sector: "Healthcare" },
  { symbol: "MRCO", name: "Misr Refrigeration & Air Conditioning", sector: "Consumer Discretionary" },
  { symbol: "MEGM", name: "Middle East Glass Manufacturing Company S.A.E.", sector: "Industrials" },
  { symbol: "MENA", name: "Mena for Touristic & Real Estate Investment", sector: "Consumer Discretionary" },
  { symbol: "MEPA", name: "Medical Packaging Company", sector: "Industrials" },
  { symbol: "MFPC", name: "Misr Fertilizer Production Company", sector: "Materials" },
  { symbol: "MFSC", name: "Egypt Free Shops Co.", sector: "Consumer Discretionary" },
  { symbol: "MHOT", name: "Misr Hotels Company", sector: "Consumer Discretionary" },
  { symbol: "MICH", name: "Misr Chemical Industries Co.", sector: "Materials" },
  { symbol: "MILS", name: "North Cairo Flour Mills", sector: "Consumer Defensive" },
  { symbol: "MIPH", name: "MINAPHARM Pharmaceuticals", sector: "Healthcare" },
  { symbol: "MMAT", name: "Marsa Marsa Alam For Tourism Development SAE", sector: "Consumer Discretionary" },
  { symbol: "MOED", name: "The Egyptian Modern Education Systems, S.A.E.", sector: "Consumer Discretionary" },
  { symbol: "MOIL", name: "Maridive and Oil Services S.A.E.", sector: "Industrials" },
  { symbol: "MOIN", name: "Mohandes Insurance Company", sector: "Financials" },
  { symbol: "MOSC", name: "Misr Oils & Soap", sector: "Consumer Defensive" },
  { symbol: "MPCI", name: "Memphis Pharmaceuticals & Chemical Industries", sector: "Healthcare" },
  { symbol: "MPCO", name: "Mansoura Poultry co.S.A.E", sector: "Consumer Defensive" },
  { symbol: "MPRC", name: "Egyptian Media Production City", sector: "Consumer Discretionary" },
  { symbol: "MTIE", name: "MM Group for Industry and International Trade S.A.E.", sector: "Consumer Discretionary" },
  { symbol: "NAHO", name: "Naeem Holding Company For Investments (S.A.E - Free Zone)", sector: "Financials" },
  { symbol: "NCEM", name: "National Cement Company", sector: "Materials" },
  { symbol: "NAPR", name: "National Printing Company S.A.E.", sector: "Industrials" },
  { symbol: "NCGC", name: "Nile Cotton Ginning", sector: "Consumer Defensive" },
  { symbol: "NCMP", name: "National Company For Maize Products", sector: "Consumer Defensive" },
  { symbol: "NARE", name: "Naeem Real Estate Holding Group", sector: "Real Estate" },
  { symbol: "NCCW", name: "Nasr Company for Civil Works", sector: "Industrials" },
  { symbol: "NDRL", name: "National Drilling Company", sector: "Energy" },
  { symbol: "NEDA", name: "Northern Upper Egypt For Development & Agricultural Production Co.", sector: "Real Estate" },
  { symbol: "NMIN", name: "El Nasr Mining Company", sector: "Materials" },
  { symbol: "NHPS", name: "National Company for Housing Professional Syndicates SAE", sector: "Real Estate" },
  { symbol: "NINH", name: "Nozha International Hospital", sector: "Healthcare" },
  { symbol: "NIPH", name: "EI- Nile Co. for Pharmaceuticals and Chemical Industries", sector: "Healthcare" },
  { symbol: "OBRI", name: "El-Ebour Co. for Real Estate Investment S.A.E.", sector: "Real Estate" },
  { symbol: "OCDI", name: "Sixth of October for Development and Investment Company \"SODIC\" (S.A.E.)", sector: "Real Estate" },
  { symbol: "OCPH", name: "October Pharma S.A.E", sector: "Healthcare" },
  { symbol: "ODIN", name: "ODIN Investments (S.A.E)", sector: "Financials" },
  { symbol: "OFH", name: "O B Financial Holding S.A.E", sector: "Financials" },
  { symbol: "OIH", name: "Orascom Investment Holding S.A.E.", sector: "Technology" },
  { symbol: "OREG", name: "Orange Egypt for Telecommunications", sector: "Technology" },
  { symbol: "OLFI", name: "Obour Land for Food Industries S.A.E.", sector: "Consumer Defensive" },
  { symbol: "ORAS", name: "Orascom Construction PLC", sector: "Industrials" },
  { symbol: "ORHD", name: "Orascom Development Egypt S.A.E.", sector: "Real Estate" },
  { symbol: "ORWE", name: "Oriental Weavers Carpets Company (S.A.E)", sector: "Consumer Defensive" },
  { symbol: "PACH", name: "Paints & Chemicals Industries (PACHIN)", sector: "Materials" },
  { symbol: "PHAR", name: "Egyptian International Pharmaceutical Industries Company", sector: "Healthcare" },
  { symbol: "PHDC", name: "Palm Hills Developments S.A.E.", sector: "Real Estate" },
  { symbol: "PHGC", name: "Premium Healthcare Group", sector: "Healthcare" },
  { symbol: "PHTV", name: "Pyramisa Hotels & Resorts", sector: "Consumer Discretionary" },
  { symbol: "POCO", name: "Port Said Containers And Cargo Handling Co.", sector: "Industrials" },
  { symbol: "RIVA", name: "Riva Pharma", sector: "Healthcare" },
  { symbol: "SBAG", name: "Suez Bags Company SAE", sector: "Industrials" },
  { symbol: "POUL", name: "Cairo Poultry Company S.A.E.", sector: "Consumer Defensive" },
  { symbol: "PRCL", name: "The General Company for Ceramic and Porcelain Products", sector: "Materials" },
  { symbol: "PRDC", name: "Pioneers Properties For Urban Development - PRE Group", sector: "Real Estate" },
  { symbol: "PRMH", name: "Prime Holding S.A.E", sector: "Financials" },
  { symbol: "QNBE", name: "Qatar National Bank", sector: "Financials" },
  { symbol: "RACC", name: "Raya Customer Experience", sector: "Industrials" },
  { symbol: "RAKT", name: "Rakta Paper Manufacturing Company", sector: "Industrials" },
  { symbol: "RAYA", name: "Raya Holding Company for Financial Investments (S.A.E)", sector: "Financials" },
  { symbol: "RMDA", name: "Tenth of Ramadan for Pharmaceutical Industries and Diagnostic Reagents (Rameda) (S.A.E)", sector: "Healthcare" },
  { symbol: "ROTO", name: "Rowad Tourism Company", sector: "Consumer Discretionary" },
  { symbol: "RREI", name: "Arab Real Estate Investment Co.", sector: "Real Estate" },
  { symbol: "RTVC", name: "Remco Tourism Villages Construction", sector: "Consumer Discretionary" },
  { symbol: "RUBX", name: "Rubex International for Plastic and Acrylic Manufacturing", sector: "Materials" },
  { symbol: "SAIB", name: "Societe Arabe Internationale de Banque S.A.E", sector: "Financials" },
  { symbol: "SAUD", name: "alBaraka Bank Egypt S.A.E.", sector: "Financials" },
  { symbol: "SCEM", name: "Sinai Cement Co. (S.A.E)", sector: "Industrials" },
  { symbol: "SCFM", name: "South Cairo and Giza Flour Mills and Bakeries Company", sector: "Consumer Defensive" },
  { symbol: "SMCS", name: "Samcrete Misr", sector: "Industrials" },
  { symbol: "SMCSA", name: "Samcrete Misr Preferred Shares", sector: "Industrials" },
  { symbol: "SRWA", name: "Sarwa Capital", sector: "Financials" },
  { symbol: "SUCE", name: "Suez Cement Company", sector: "Materials" },
  { symbol: "SCTS", name: "Suez Canal Company for Technology Settling (S.A.E)", sector: "Technology" },
  { symbol: "SDTI", name: "SHARM DREAMS Co. for Touristic Investment S.A.E", sector: "Consumer Discretionary" },
  { symbol: "SEIG", name: "Saudi Egyptian Investment & Finance Co. S.A.E", sector: "Financials" },
  { symbol: "SEIGA", name: "Saudi Egyptian Investment & Finance Co. (Preferred)", sector: "Financials" },
  { symbol: "SIPC", name: "Sabaa International Company for Pharmaceutical and Chemical Industry", sector: "Healthcare" },
  { symbol: "SKPC", name: "Sidi Kerir Petrochemicals Co.", sector: "Materials" },
  { symbol: "SMFR", name: "Samad Misr EGYFERT.S.A.E", sector: "Materials" },
  { symbol: "SNFC", name: "Sharkia National Company for Food Security", sector: "Consumer Defensive" },
  { symbol: "SPHT", name: "El Shams Pyramids Co. For Hotels & Touristic Projects S.A.E", sector: "Consumer Discretionary" },
  { symbol: "SPIN", name: "Alexandria Spinning & Weaving Co.", sector: "Consumer Discretionary" },
  { symbol: "SPMD", name: "Speed Medical Co", sector: "Healthcare" },
  { symbol: "TECH", name: "Taghleef Industries - Egypt", sector: "Industrials" },
  { symbol: "SUGR", name: "Delta Sugar Company", sector: "Consumer Defensive" },
  { symbol: "SVCE", name: "South Valley Cement Company", sector: "Industrials" },
  { symbol: "SWDY", name: "El Sewedy Electric Company", sector: "Industrials" },
  { symbol: "TALM", name: "Taaleem Management Services Company S.A.E.", sector: "Consumer Discretionary" },
  { symbol: "TANM", name: "Tanmiya For Real Estate Investment (S.A.E)", sector: "Real Estate" },
  { symbol: "TAQA", name: "TAQA Arabia S.A.E.", sector: "Industrials" },
  { symbol: "TMGH", name: "Talaat Moustafa Group Holding", sector: "Real Estate" },
  { symbol: "TRTO", name: "Trans Oceans Tours", sector: "Consumer Discretionary" },
  { symbol: "UBEE", name: "The United Bank", sector: "Financials" },
  { symbol: "UTOP", name: "Utopia Real Estate Investment and Tourism", sector: "Real Estate" },
  { symbol: "UEFM", name: "Upper Egypt Mills Company J.S.C", sector: "Industrials" },
  { symbol: "UEGC", name: "El-Saeed Company for Contracting and Real Estate Investment \"SCCD\" (S.A.E.)", sector: "Industrials" },
  { symbol: "UNIP", name: "Universal For Paper and Packaging Materials", sector: "Industrials" },
  { symbol: "UNIT", name: "United Co. for Housing & Development - S.A.E.", sector: "Real Estate" },
  { symbol: "VALU", name: "U Consumer Finance S.A.E.", sector: "Financials" },
  { symbol: "VLMR", name: "Valmore Holding S.A.E.", sector: "Industrials" },
  { symbol: "VLMRA", name: "Valmore Holding S.A.E. (Preferred)", sector: "Industrials" },
  { symbol: "VERT", name: "Vertika for Industry & Trade", sector: "Industrials" },
  { symbol: "VODE", name: "Vodafone Egypt Telecommunications SAE", sector: "Technology" },
  { symbol: "WCDF", name: "Middle & West Delta Flour Mills", sector: "Consumer Defensive" },
  { symbol: "WKOL", name: "Wadi Kom Ombo For Land Reclamation Co.", sector: "Industrials" },
  { symbol: "ZEOT", name: "Extracted Oil & Derivatives Co.", sector: "Industrials" },
  { symbol: "ZMID", name: "Zahraa El Maadi Investment and Development Company SAE", sector: "Real Estate" },
];

export const EGX_STOCK_COUNT = EGX_STOCKS.length; // 259 unique stocks

// ── Helper: Find stock by symbol or name ────────────────────────
export function findStock(symbolOrName: string): (typeof EGX_STOCKS)[number] | undefined {
  const q = symbolOrName.toUpperCase().trim();
  return EGX_STOCKS.find(s => s.symbol === q) ||
    EGX_STOCKS.find(s => s.name.toUpperCase().includes(q));
}

// ── Helper: Search stocks by query ──────────────────────────────
export function searchStocks(query: string, limit = 20): (typeof EGX_STOCKS)[number][] {
  if (!query) return EGX_STOCKS.slice(0, limit);
  const q = query.toUpperCase().trim();
  return EGX_STOCKS
    .filter(s => s.symbol.includes(q) || s.name.toUpperCase().includes(q))
    .slice(0, limit);
}
